@startuml
'https://plantuml.com/sequence-diagram

class Products{
- products : ArrayList<Product>
- stringRepr : StringBuilder
- match : product
}
class productSearch{
- products -> Products
- gson : Gson
- match : Product
- app : ProductSearch
}
@enduml