@startuml
'https://plantuml.com/sequence-diagram

Class Exercise46{
- inputPath = String
- wTable = WordTable
}

Class WordCounter{
- word : String
- count : int
}

Class WordTable{
- wordCounts : HashMap<String, WordCounter>
- inputPath : String
- maxWordLength : int
+ word : String
+ counts : List<WordCounter>
}
@enduml